version: "3.3"

services:
  mariadb:
      image: mariadb:10.5.8
      container_name: mariadb
      restart: always
      networks:
        - solution_net
      ports:
          - 3306:3306
      environment:
          - MYSQL_ROOT_PASSWORD=87654321d
          - MYSQL_USER=judge
          - MYSQL_PASSWORD=12345678
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  phpmyadmin:
      image: phpmyadmin:latest 
      container_name: phpmyadmin
      networks:
        - solution_net
      environment:
          - PMA_HOST=mariadb
          - PMA_USER=root
          - PMA_PASSWORD=87654321
      restart: always
      ports:
          - 8080:80
networks:
  solution_net:
    driver: bridge