version: '3.6'
services:
    mariadb:
        image: mariadb:latest
        restart: always
        volumes: E:/
        ports: 
            - "3306:3306"

        environment: 
            - MYSQL_ROOT_PASSWORD: 123456

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        volumes: 
        ports: 
            - "8080:8080"
        environment: 
            - MYSQL_ROOT_PASSWORD: 123456